### ISSUE TITLE
docker建立项目时提示tomcat包404，第一次用见谅。。不知道怎么处理

### ISSUE THREAD

**Issue by eeeeeeeason** [anyesu/websocket#1]
--2018-08-04 15:15:33--  http://mirror.bit.edu.cn/apache/tomcat/tomcat-7/v7.0.82/bin/apache-tomcat-7.0.82.tar.gz
Resolving mirror.bit.edu.cn... 202.204.80.77, 2001:da8:204:2001:250:56ff:fea1:22
Connecting to mirror.bit.edu.cn|202.204.80.77|:80... connected.
HTTP request sent, awaiting response... 404 Not Found
2018-08-04 15:15:33 ERROR 404: Not Found.

**Comment by eeeeeeeason** [comment]
npm install ws@1.1.0 
npm install express
node server.js
解决了，但是想学学DOCKER

**Comment by anyesu** [comment]
镜像站下载地址失效了，去tomcat官网找个可用的下载地址替换下。或者直接用tomcat的官方镜像构建。我的简书上有docker相关的[笔记](https://www.jianshu.com/nb/13876015)，可以参考下。 @eeeeeeeason

**Comment by phy25** [comment]
亲，mirror.bit.edu.cn 只同步最新的一个版本哦，请访问 http://mirror.bit.edu.cn/apache/tomcat/tomcat-7/ 下载最新版 Tomcat。
