### ISSUE TITLE
兄弟,这个能用吗?

### ISSUE THREAD

**Issue by 123wangfei** [anyesu/websocket#3]
这能用吗???

**Comment by anyesu** [comment]
@123wangfei 抱歉一直没看到，回复迟了。

虽然是很老的项目了，但我刚刚重新拉下来跑了一遍，能正常用的：

- clone 项目并用 IDEA 打开

- 打开运行配置 `Run/Debug Configurations`

- 添加 Tomcat

  `Add New Configuration` > `Tomcat Server ` > `Local` > `Application server` > `Configure` > 选择本地安装路径。

- 添加项目到 Tomcat 中

  `Deployment` > `Add` > `Artifact` > `websocket-chat` 项目随便选择一种部署方式 > `Application context` 修改为 `/` > `Apply`

- 运行 Tomcat

- 浏览器打开 http://127.0.0.1:8080

测试视频效果的话需要用旧版的 [火狐](https://ftp.mozilla.org/pub/firefox/releases/45.0.2/win64/zh-CN/) ，新版浏览器的 **API** 有变动和限制。

[websocket-samples](https://github.com/anyesu/websocket/tree/master/websocket-samples) 子项目是 [文章](https://www.jianshu.com/p/03a74d489f34) 最初配套的 demo ，是那种老的项目结构，导入步骤稍微麻烦点，可以参考下文章的彩蛋部分。

node 项目（ 公网 WebRTC 服务器已失效 ）需要手动安装依赖包再运行启动脚本。

```shell
npm install ws@1.1.0 express
```

这个 issue 我先关闭了，有需要再打开。
